### ISSUE TITLE
Package.json malformed

### ISSUE THREAD

**Issue by toolbuilder** [gliese1337/priority-deque#1]
The `package.json` file refers to files with `priority-queue` in the name. The package dist directory provides files with `priority-deque` in the name. As a result, Node can't find the files to run. I temporarily modified `package.json` and Node could then find the files.

```json
  "main": "dist/priority-queue.js",
  "types": "dist/priority-queue.d.ts",
```

**Comment by gliese1337** [comment]
Whoops! Thanks for noticing. It should be updated on NPM now.
